services:

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secretpass
      POSTGRES_USER: username
      POSTGRES_DB: mlflow_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  mlflow:
    build: ./mlflow
    environment:
      BACKEND_STORE_URI: postgresql://username:secretpass@db:5432/mlflow_db
    ports:
      - 5001:5000
    volumes:
      - mlartifacts:/mlartifacts
    depends_on:
      - db

  training:
    build: ./training
    volumes:
      - ./training/data:/app/data
      - ./training:/app
    depends_on:
      - mlflow

  api-v1:
    build:
      context: ./serving
      dockerfile: v1/Dockerfile
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_URI: models:/imdb-sentiment-v1/1
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mlflow

  api-v2:
    build:
      context: ./serving
      dockerfile: v2/Dockerfile
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_URI: models:/imdb-sentiment-v2/2
    ports:
      - 8001:8000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mlflow

volumes:
  pgdata:
  mlartifacts:
    